import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from utils import *

import argparse


SUBDIR = "PersonalScripts"

help_message = f'''
{FLYellow}==================== SCRIPT TO APP ===================={CRst}
{FLYellow}Description:{CRst}
  Create a Windows .cmd launcher for a Python script under Program Files.
  The generated .cmd can be selected from "Open with" and receives opened
  file paths as command-line arguments.

{FLYellow}Examples:{CRst}
  {FGray}# Full CLI usage{CRst}
  python script-to-app.py --target-script C:\\tools\\my-tool.py --app-name MyTool

  {FGray}# Interactive mode (no arguments){CRst}
  python script-to-app.py

{FLYellow}Windows only. Run as Administrator when writing to Program Files.{CRst}
'''


def _title_case(name: str) -> str:
    return name.replace("_", " ").replace("-", " ").title().replace(" ", "")


def _escape_cmd_set_value(value: str) -> str:
    """Escape a value embedded in a batch ``set "NAME=value"`` statement."""
    return value.replace("%", "%%")


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create a Windows .cmd launcher wrapping a Python script.",
        epilog=help_message,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--target-script", dest="target_script",
        help="Path to the Python script to wrap into a .cmd launcher",
    )
    parser.add_argument(
        "--app-name", dest="app_name",
        help="Name for the .cmd launcher (default: derived from script filename)",
    )
    parser.add_argument(
        "--output-dir", dest="output_dir",
        help=r"Directory for the launcher (default: %ProgramFiles%\PersonalScripts)",
    )
    return parser


def _resolve_target_script(arg_value: str | None) -> str:
    if arg_value:
        p = os.path.abspath(os.path.expanduser(arg_value))
        if not os.path.isfile(p):
            Utils.print_error_and_exit(f"Target script not found: {p}")
        if os.path.splitext(p)[1].lower() != ".py":
            Utils.print_error_and_exit(f"Target script must be a .py file: {p}")
        return p
    p = Input.resolve_input_path(
        default_path=os.path.expanduser("~"),
        prompt="Path to the Python script to wrap",
        path_type="file",
    )
    if os.path.splitext(p)[1].lower() != ".py":
        Utils.print_error_and_exit(f"Target script must be a .py file: {p}")
    return p


def _resolve_app_name(arg_value: str | None, script_path: str) -> str:
    if arg_value:
        return arg_value
    stem = os.path.splitext(os.path.basename(script_path))[0]
    default_name = _title_case(stem)
    name = input(
        f"{FLYellow}Launcher name {FGray}[{default_name}]{CRst}: "
    ).strip()
    return name or default_name


def _resolve_output_dir(arg_value: str | None) -> str:
    if arg_value:
        return os.path.abspath(os.path.expanduser(arg_value))
    program_files = os.environ.get("ProgramFiles", r"C:\Program Files")
    return os.path.join(program_files, SUBDIR)


def _build_launcher_content(target_script: str) -> str:
    escaped_python_exe = _escape_cmd_set_value(sys.executable)
    escaped_target_script = _escape_cmd_set_value(target_script)
    return f'''@echo off
REM ============================================
REM  Python script launcher generated by script-to-app.py
REM ============================================

chcp 65001 >nul

set "PYTHON={escaped_python_exe}"
set "TARGET_SCRIPT={escaped_target_script}"

if "%~1"=="" (
    "%PYTHON%" "%TARGET_SCRIPT%" %*
    pause
) else (
    "%PYTHON%" "%TARGET_SCRIPT%" %*
    if ERRORLEVEL 1 (
        echo.
        echo Script exited with error code: %ERRORLEVEL%
        pause
    )
)
'''


def _write_launcher(launcher_path: str, target_script: str) -> None:
    content = _build_launcher_content(target_script)
    with open(launcher_path, "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write(content)


def main(argv: list[str] | None = None) -> int:
    if sys.platform != "win32":
        Utils.print_error_and_exit("This script only works on Windows.")

    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    if len(sys.argv) == 1:
        print(help_message)

    target_script = _resolve_target_script(args.target_script)
    app_name = _resolve_app_name(args.app_name, target_script)

    if not app_name.lower().endswith(".cmd"):
        app_name += ".cmd"

    output_dir = _resolve_output_dir(args.output_dir)
    launcher_path = os.path.join(output_dir, app_name)

    while os.path.exists(launcher_path):
        print()
        print(f"{FLYellow}{launcher_path}{CRst} {FLRed}already exists.{CRst}")
        choice = input(f"Overwrite? [y/N] or enter a new name: ").strip()
        if choice.lower() in ("y", "yes"):
            break
        elif choice:
            if not choice.lower().endswith(".cmd"):
                choice += ".cmd"
            launcher_path = os.path.join(output_dir, choice)
        else:
            print(f"{FLRed}Cancelled.{CRst}")
            return 0

    print()
    print(f"{FLYellow}  Target script  :{CRst} {FLCyan}{target_script}{CRst}")
    print(f"{FLYellow}  Launcher path  :{CRst} {FLCyan}{launcher_path}{CRst}")
    print(f"{FLYellow}  Python path    :{CRst} {FLCyan}{sys.executable}{CRst}")
    print()

    confirm = input(f"{FLYellow}Create this .cmd launcher?{CRst} [Y/n]: ").strip().lower()
    if confirm and confirm not in ("y", "yes"):
        print(f"{FLRed}Cancelled.{CRst}")
        return 0

    try:
        os.makedirs(output_dir, exist_ok=True)
        _write_launcher(launcher_path, target_script)
    except PermissionError:
        Utils.print_error_and_exit(
            f"Permission denied: {output_dir}. Run this script as Administrator or use --output-dir."
        )

    print(f"{FLGreen}Created:{CRst} {FLCyan}{launcher_path}{CRst}")
    print()
    print(f"{FLYellow}Usage:{CRst}")
    print("  Right-click a file -> Open with -> Choose another app ->")
    print(f"  select {FLCyan}{launcher_path}{CRst}")
    return 0


if __name__ == "__main__":
    raise sys.exit(main())
